// src/app/components/footer/footer.tsx
import React from 'react';
import styles from './footer.module.scss';
import Link from 'next/link';

const Footer: React.FC = () => {
  return (
    <div className={styles.container}>
      <span>A game by &nbsp;</span>
      <Link href="https://www.codyroberts.net/">Cody Roberts</Link>
      <span>&nbsp; | &nbsp;</span>
      <span>Game art by &nbsp;</span>
      <Link href="https://www.patreon.com/c/krishna_palacio/">
        Krishna Palacio
      </Link>
      <span>&nbsp; | &nbsp;</span>
      <span>Website art by &nbsp;</span>
      <Link href="https://www.patreon.com/StockArt">Rick Hershey</Link>
    </div>
  );
};

export default Footer;

// qwik-app/src/components/footer/footer.tsx
import { component$ } from "@builder.io/qwik";
import styles from "./footer.module.css";

export default component$(() => {

  return (
    <footer>
      <div class="container">
        <a href="https://www.github.com/codyroberts" target="_blank" class={styles.anchor}>
          <span>A game by</span> <span class={styles.highlight}>Cody Roberts</span>
          <span class={styles.spacer}>|</span>
          <span>Art by </span> <span class={styles.highlight}>Rick Hershey</span>
        </a>
      </div>
    </footer>
  );
});
